# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 pre = "blogger"
 name = "Blog"
 weight = 10
 url = "/posts"

[[main]]
 pre = "list"
 name = "Notes"
 weight = 10

[[main]]
 pre = "lightbulb"
 name = "Projects"
 pageRef = "projects"
 weight = 10
 url = "/projects"

[[main]]
  pre = "graduation-cap"
  name = "About"
  weight = 10
  url = "/about"

[[main]]
  name = "Physics"
  pre = "sun"
  parent = "Notes"
  weight = 11
  url = "/notes/physics"

[[main]]
  name = "Programming"
  pre = "code"
  parent = "Notes"
  weight = 12
  url = "/notes/programming"

[[main]]
  idnetifier = "github"
  pre = "github"
  url = "https://github.com/daVimci"
  weight = 15

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 10
